"""create initial schema

Revision ID: 0012d9958515
Revises:
Create Date: 2026-09-23 14:08:13.048185
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "0012d9958515"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "approved_sources",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("html", "pdf", "docx", "webpage", name="source_type"),
            nullable=False,
        ),
        sa.Column("issuing_office", sa.String(length=255), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "approved",
                "pending_review",
                "rejected",
                "superseded",
                name="review_status",
            ),
            nullable=False,
        ),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "review_status != 'approved' OR is_active",
            name="ck_approved_sources_approved_must_be_active",
        ),
        sa.CheckConstraint(
            "review_status != 'superseded' OR superseded_by IS NOT NULL",
            name="ck_approved_sources_superseded_by_required",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"], ["approved_sources.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_base_releases",
        sa.Column(
            "status",
            sa.Enum(
                "preparing",
                "validated",
                "active",
                "rejected",
                "retired",
                name="release_status",
            ),
            nullable=False,
        ),
        sa.Column("embedding_model", sa.String(length=255), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_knowledge_base_releases_one_active",
        "knowledge_base_releases",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "student_questions",
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column(
            "student_type",
            sa.Enum("undergraduate", "graduate", "unknown", name="student_type"),
            nullable=False,
        ),
        sa.Column("asked_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(raw_text)) > 0", name="ck_student_questions_raw_text_nonempty"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grounded_answers",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "response_type",
            sa.Enum(
                "direct_answer",
                "clarification_needed",
                "safe_referral",
                name="response_type",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name="ck_grounded_answers_confidence_range",
        ),
        sa.CheckConstraint(
            "length(trim(answer_text)) > 0",
            name="ck_grounded_answers_answer_text_nonempty",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["student_questions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parsing_review_records",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "issue_type",
            sa.Enum(
                "parse_failure",
                "inaccessible_source",
                "conflicting_metadata",
                "invalid_format",
                "missing_structure",
                name="parsing_issue_type",
            ),
            nullable=False,
        ),
        sa.Column("issue_details", sa.Text(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "pending",
                "reviewed",
                "rejected",
                "accepted_with_warning",
                name="parsing_review_status",
            ),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(issue_details)) > 0",
            name="ck_parsing_review_records_issue_details_nonempty",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["approved_sources.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preparation_validations",
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("check_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("passed", "failed", "warning", name="validation_status"),
            nullable=False,
        ),
        sa.Column("measured_value", sa.String(length=255), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(check_name)) > 0",
            name="ck_preparation_validations_check_name_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(details)) > 0",
            name="ck_preparation_validations_details_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(measured_value)) > 0",
            name="ck_preparation_validations_measured_value_nonempty",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"], ["knowledge_base_releases.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_content_segments",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("source_snippet", sa.Text(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False
        ),
        sa.Column("structural_path", sa.String(length=1000), nullable=False),
        sa.Column(
            "content_kind",
            sa.Enum(
                "heading",
                "paragraph",
                "table",
                "list",
                "sidebar",
                "callout",
                "continuation",
                name="content_kind",
            ),
            nullable=False,
        ),
        sa.Column("location_label", sa.String(length=500), nullable=False),
        sa.Column("chunk_hash", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "chunk_index >= 0",
            name="ck_source_content_segments_chunk_index_nonnegative",
        ),
        sa.CheckConstraint(
            "length(trim(chunk_hash)) > 0",
            name="ck_source_content_segments_chunk_hash_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(content_text)) > 0",
            name="ck_source_content_segments_content_text_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(location_label)) > 0",
            name="ck_source_content_segments_location_label_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(structural_path)) > 0",
            name="ck_source_content_segments_structural_path_nonempty",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"], ["knowledge_base_releases.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["approved_sources.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer_citations",
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("citation_text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(citation_text)) > 0",
            name="ck_answer_citations_citation_text_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(source_url)) > 0",
            name="ck_answer_citations_source_url_nonempty",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["grounded_answers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["source_content_segments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["approved_sources.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "safe_referrals",
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("office_name", sa.String(length=255), nullable=False),
        sa.Column("referral_reason", sa.Text(), nullable=False),
        sa.Column("contact_url", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(contact_url)) > 0",
            name="ck_safe_referrals_contact_url_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(office_name)) > 0",
            name="ck_safe_referrals_office_name_nonempty",
        ),
        sa.CheckConstraint(
            "length(trim(referral_reason)) > 0",
            name="ck_safe_referrals_reason_nonempty",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["grounded_answers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("answer_id", name="uq_safe_referrals_answer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("safe_referrals")
    op.drop_table("answer_citations")
    op.drop_table("source_content_segments")
    op.drop_table("preparation_validations")
    op.drop_table("parsing_review_records")
    op.drop_table("grounded_answers")
    op.drop_table("student_questions")
    op.drop_index(
        "uq_knowledge_base_releases_one_active",
        table_name="knowledge_base_releases",
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.drop_table("knowledge_base_releases")
    op.drop_table("approved_sources")
    # ### end Alembic commands ###
